import { prisma } from "../lib/prisma.js";
import { slugifyText } from "../lib/helpers.js";

const IMG = {
  game_hero: "https://images.unsplash.com/photo-1698450998458-0bc1045788a1?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODF8MHwxfHNlYXJjaHwxfHx2aWRlbyUyMGdhbWUlMjBmYW50YXN5JTIwc2NyZWVuc2hvdHxlbnwwfHx8fDE3ODMzNDY1MDJ8MA&ixlib=rb-4.1.0&q=85",
  game_2: "https://images.unsplash.com/photo-1608741869829-8eb30661c7be?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODF8MHwxfHNlYXJjaHwyfHx2aWRlbyUyMGdhbWUlMjBmYW50YXN5JTIwc2NyZWVuc2hvdHxlbnwwfHx8fDE3ODMzNDY1MDJ8MA&ixlib=rb-4.1.0&q=85",
  game_3: "https://images.unsplash.com/photo-1672872476232-da16b45c9001?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2NDF8MHwxfHNlYXJjaHwyfHxjeWJlcnB1bmslMjBjaXR5JTIwZGFyayUyMG5pZ2h0fGVufDB8fHx8MTc4MzM0NjUwMnww&ixlib=rb-4.1.0&q=85",
  game_4: "https://images.unsplash.com/photo-1552820728-8b83bb896128?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
  game_5: "https://images.unsplash.com/photo-1511512578047-dfb367046420?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
  dapp_1: "https://images.unsplash.com/photo-1666875753105-c63a6f3bdc86?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2NDJ8MHwxfHNlYXJjaHwyfHxtb2Rlcm4lMjBkYXNoYm9hcmQlMjBhbmFseXRpY3MlMjBhcHB8ZW58MHx8fHwxNzgzMzQ2NTAyfDA&ixlib=rb-4.1.0&q=85",
  dapp_2: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2NDF8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBkYXNoYm9hcmQlMjBhbmFseXRpY3MlMjBhcHB8ZW58MHx8fHwxNzgzMzQ2NTAyfDA&ixlib=rb-4.1.0&q=85",
  dapp_3: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
  dapp_4: "https://images.unsplash.com/photo-1620321023374-d1a68fbc720d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
  dapp_5: "https://images.unsplash.com/photo-1642104704074-907c0698cbd9?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
  blog_1: "https://images.unsplash.com/photo-1654198340681-a2e0fc449f1b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2OTV8MHwxfHNlYXJjaHwzfHxhYnN0cmFjdCUyMGRhcmslMjBuZW9uJTIwYmx1ZSUyMHB1cnBsZSUyMHRlY2hub2xvZ3l8ZW58MHx8fHwxNzgzMzQ2NTAyfDA&ixlib=rb-4.1.0&q=85",
  blog_2: "https://images.unsplash.com/photo-1563089145-599997674d42?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2OTV8MHwxfHNlYXJjaHwyfHxhYnN0cmFjdCUyMGRhcmslMjBuZW9uJTIwYmx1ZSUyMHB1cnBsZSUyMHRlY2hub2xvZ3l8ZW58MHx8fHwxNzgzMzQ2NTAyfDA&ixlib=rb-4.1.0&q=85",
  blog_3: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
  blog_4: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
  blog_5: "https://images.unsplash.com/photo-1639322537228-f710d846310a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
  logo: "https://images.unsplash.com/photo-1620321023374-d1a68fbc720d?crop=entropy&cs=srgb&fm=jpg&q=85&w=200",
};

const games = [
  {
    title: "Crypto Legends",
    shortDesc: "An epic RPG adventure set in a decentralized world. Play, earn and own your journey.",
    description:
      "Crypto Legends is a blockchain RPG game where players explore a vast world, complete quests, collect NFTs and battle monsters. All assets are owned by players and can be traded in the marketplace.",
    blockchain: "Ethereum",
    category: "RPG",
    banner: IMG.game_hero,
    thumbnail: IMG.game_hero,
    logo: IMG.logo,
    website: "https://cryptolegends.game",
    github: "https://github.com/etherauthority/crypto-legends",
    videoUrl: "",
    features: [
      "True asset ownership with NFTs",
      "Play-to-earn economy",
      "Exciting quests and gameplay",
      "Built on Ethereum blockchain",
    ],
    techStack: ["Solidity", "React", "IPFS", "The Graph"],
    gallery: [IMG.game_2, IMG.game_3, IMG.game_4],
    rank: 1,
    views: 24500,
    likes: 12300,
    featured: true,
    status: "APPROVED",
  },
  {
    title: "Chain Empires",
    shortDesc: "Build, conquer and rule the decentralized world.",
    description: "A strategy game where players build kingdoms, forge alliances and battle for glory across chains.",
    blockchain: "Polygon",
    category: "Strategy",
    banner: IMG.game_2,
    thumbnail: IMG.game_2,
    logo: IMG.logo,
    website: "https://chainempires.io",
    features: ["Cross-chain battles", "NFT armies", "Guild wars"],
    techStack: ["Unity", "Solidity", "Polygon SDK"],
    gallery: [IMG.game_3, IMG.game_4],
    rank: 2,
    views: 18700,
    likes: 8900,
    status: "APPROVED",
  },
  {
    title: "Battle Cards",
    shortDesc: "Collect, trade and battle with unique cards.",
    description: "A collectible card game where every card is an NFT with unique abilities and rarities.",
    blockchain: "BNB Chain",
    category: "Card",
    banner: IMG.game_3,
    thumbnail: IMG.game_3,
    logo: IMG.logo,
    website: "https://battlecards.gg",
    features: ["NFT card packs", "Ranked ladder", "Weekly tournaments"],
    techStack: ["React", "Solidity", "Node.js"],
    gallery: [IMG.game_4, IMG.game_hero],
    rank: 3,
    views: 15200,
    likes: 7100,
    status: "APPROVED",
  },
  {
    title: "Meta Racers",
    shortDesc: "High speed NFT racing experience.",
    description: "Race NFT cars on procedurally generated tracks. Own, upgrade and trade your vehicles.",
    blockchain: "Avalanche",
    category: "Racing",
    banner: IMG.game_4,
    thumbnail: IMG.game_4,
    logo: IMG.logo,
    website: "https://metaracers.xyz",
    features: ["Live PvP racing", "Custom garages", "Sponsorships"],
    techStack: ["Unreal Engine", "Avalanche SDK"],
    gallery: [IMG.game_5, IMG.game_hero],
    rank: 4,
    views: 15200,
    likes: 7100,
    status: "APPROVED",
  },
  {
    title: "Lost Realms",
    shortDesc: "Explore mysterious realms and earn rewards.",
    description: "Adventure through fantastical worlds, defeat mythical beasts and claim epic loot as NFTs.",
    blockchain: "Solana",
    category: "Adventure",
    banner: IMG.game_5,
    thumbnail: IMG.game_5,
    logo: IMG.logo,
    website: "https://lostrealms.io",
    features: ["Open-world exploration", "Loot drops", "Fast Solana txs"],
    techStack: ["Unity", "Rust", "Solana"],
    gallery: [IMG.game_hero, IMG.game_2],
    rank: 5,
    views: 9300,
    likes: 4200,
    status: "APPROVED",
  },
  {
    title: "Skyline Warriors",
    shortDesc: "Team-based tactical action in the metaverse.",
    description: "Tactical shooter with cross-chain economies and cosmetic NFTs.",
    blockchain: "Ethereum",
    category: "Action",
    banner: IMG.game_hero,
    thumbnail: IMG.game_hero,
    logo: IMG.logo,
    features: ["5v5 matches", "Cosmetic NFTs"],
    techStack: ["Unity"],
    gallery: [IMG.game_2],
    rank: 6,
    views: 7200,
    likes: 3300,
    status: "APPROVED",
  },
];

const dapps = [
  {
    title: "StakeHub",
    shortDesc: "A decentralized staking platform.",
    description: "Stake across multiple protocols with one click. Auto-compounding vaults and detailed analytics.",
    blockchain: "Ethereum",
    category: "DeFi",
    banner: IMG.dapp_1,
    thumbnail: IMG.dapp_1,
    logo: IMG.logo,
    website: "https://stakehub.xyz",
    features: ["Auto-compounding", "Multi-chain", "Real-time analytics"],
    techStack: ["Solidity", "React", "Ethers.js"],
    gallery: [IMG.dapp_2, IMG.dapp_3],
    rank: 1,
    views: 32100,
    likes: 11200,
    featured: true,
    status: "APPROVED",
  },
  {
    title: "VoteChain",
    shortDesc: "Decentralized voting made transparent.",
    description: "On-chain governance platform with delegation, snapshots and privacy-preserving votes.",
    blockchain: "Polygon",
    category: "DAO",
    banner: IMG.dapp_2,
    thumbnail: IMG.dapp_2,
    logo: IMG.logo,
    website: "https://votechain.io",
    features: ["Delegated voting", "Snapshots", "Privacy proofs"],
    techStack: ["Solidity", "Next.js"],
    gallery: [IMG.dapp_3],
    rank: 2,
    views: 21400,
    likes: 9600,
    status: "APPROVED",
  },
  {
    title: "NFT Launchpad",
    shortDesc: "Launch and discover NFT projects.",
    description: "Turn-key NFT launchpad with vetted projects and community curation.",
    blockchain: "BNB Chain",
    category: "NFT",
    banner: IMG.dapp_3,
    thumbnail: IMG.dapp_3,
    logo: IMG.logo,
    website: "https://nftlaunchpad.app",
    features: ["Whitelist mgmt", "Vested drops"],
    techStack: ["React", "Solidity"],
    gallery: [IMG.dapp_4],
    rank: 3,
    views: 17600,
    likes: 9600,
    status: "APPROVED",
  },
  {
    title: "Chain Analyzer",
    shortDesc: "Analyze blockchain data in real-time.",
    description: "Powerful on-chain analytics with dashboards, alerts and API access.",
    blockchain: "Ethereum",
    category: "Tools",
    banner: IMG.dapp_4,
    thumbnail: IMG.dapp_4,
    logo: IMG.logo,
    website: "https://chainanalyzer.app",
    features: ["Custom dashboards", "Alerts", "API"],
    techStack: ["Node.js", "The Graph"],
    gallery: [IMG.dapp_5],
    rank: 4,
    views: 14300,
    likes: 6100,
    status: "APPROVED",
  },
  {
    title: "Web3 Connect",
    shortDesc: "Connect, chat and earn in web3 space.",
    description: "Web3-native social network with token-gated communities and reputation.",
    blockchain: "Arbitrum",
    category: "Social",
    banner: IMG.dapp_5,
    thumbnail: IMG.dapp_5,
    logo: IMG.logo,
    website: "https://web3connect.social",
    features: ["Token gating", "On-chain identities", "Rewards"],
    techStack: ["Next.js", "Solidity"],
    gallery: [IMG.dapp_1],
    rank: 5,
    views: 12900,
    likes: 4700,
    status: "APPROVED",
  },
  {
    title: "SwapForge",
    shortDesc: "Aggregated DEX with best-price routing.",
    description: "Meta-aggregator that finds the best swap route across dozens of DEXs.",
    blockchain: "Ethereum",
    category: "DeFi",
    banner: IMG.dapp_1,
    thumbnail: IMG.dapp_1,
    logo: IMG.logo,
    features: ["Best price routing", "Gas optimization"],
    techStack: ["Solidity"],
    gallery: [],
    rank: 6,
    views: 8800,
    likes: 3100,
    status: "APPROVED",
  },
];

const blogs = [
  {
    title: "EtherAuthority Interns – Building the Future of Web3",
    excerpt:
      "Welcome to EtherAuthority Interns! We're a group of passionate builders working on exciting blockchain projects.",
    content:
      "<h2>Introducing our program</h2><p>Welcome to EtherAuthority Interns! We're a group of passionate builders working on exciting blockchain projects. Over the past months, our interns have shipped multiple production dApps and games, from DeFi tools to on-chain RPGs.</p><p>In this post, we'll share the journey, the wins, and the lessons learned by our talented team.</p>",
    category: "Announcements",
    tags: ["intro", "web3", "interns"],
    thumbnail: IMG.blog_1,
    banner: IMG.blog_1,
    readingTime: 5,
    status: "PUBLISHED",
    featured: true,
  },
  {
    title: "Top 5 Games Built by Our Incredible Interns",
    excerpt: "Here are 5 amazing blockchain games built by our talented interns.",
    content:
      "<h2>The lineup</h2><p>Our interns have built 5 stunning blockchain games that push the boundaries of on-chain gameplay. From Crypto Legends to Meta Racers, discover them all.</p>",
    category: "Updates",
    tags: ["games", "showcase"],
    thumbnail: IMG.blog_2,
    banner: IMG.blog_2,
    readingTime: 4,
    status: "PUBLISHED",
  },
  {
    title: "How to Build Your First dApp on Ethereum",
    excerpt: "A step-by-step guide for interns and beginners to build their first dApp.",
    content:
      "<h2>Setup</h2><p>Install Hardhat, MetaMask, and set up a React project.</p><h2>Contract</h2><p>Write a minimal ERC-20 contract, deploy to Sepolia and integrate with your frontend using Ethers.js.</p>",
    category: "Tutorials",
    tags: ["tutorial", "dapp"],
    thumbnail: IMG.blog_3,
    banner: IMG.blog_3,
    readingTime: 7,
    status: "PUBLISHED",
  },
  {
    title: "The Future of Gaming is Decentralized",
    excerpt: "Why blockchain gaming is the next big revolution in the gaming industry.",
    content:
      "<h2>Ownership</h2><p>Web3 gaming shifts asset ownership back to the player, unlocking real economies and portable identities across titles.</p>",
    category: "Web3",
    tags: ["gaming", "future"],
    thumbnail: IMG.blog_4,
    banner: IMG.blog_4,
    readingTime: 6,
    status: "PUBLISHED",
  },
  {
    title: "New dApp Project: VoteChain",
    excerpt: "VoteChain is a decentralized voting platform built for transparency.",
    content:
      "<h2>What is VoteChain?</h2><p>VoteChain enables secure, transparent, and privacy-preserving voting for DAOs, communities, and organizations.</p>",
    category: "Updates",
    tags: ["dao", "governance"],
    thumbnail: IMG.blog_5,
    banner: IMG.blog_5,
    readingTime: 4,
    status: "PUBLISHED",
  },
  {
    title: "Intern Spotlight: Amazing Builders of EtherAuthority",
    excerpt: "Let's shine a light on our talented interns and their incredible work.",
    content:
      "<h2>Meet the team</h2><p>Meet the builders behind our top projects. From smart contract wizards to frontend artists, our interns represent the future of Web3.</p>",
    category: "Announcements",
    tags: ["team", "spotlight"],
    thumbnail: IMG.blog_1,
    banner: IMG.blog_1,
    readingTime: 3,
    status: "PUBLISHED",
  },
];

export async function seedDemoContent() {
  const gCount = await prisma.game.count();
  const dCount = await prisma.dapp.count();
  const bCount = await prisma.blog.count();

  if (gCount === 0) {
    for (const g of games) {
      await prisma.game.create({ data: { ...g, slug: slugifyText(g.title) } });
    }
    console.log(`[seed] inserted ${games.length} games`);
  }
  if (dCount === 0) {
    for (const d of dapps) {
      await prisma.dapp.create({ data: { ...d, slug: slugifyText(d.title) } });
    }
    console.log(`[seed] inserted ${dapps.length} dapps`);
  }
  if (bCount === 0) {
    for (const b of blogs) {
      await prisma.blog.create({
        data: { ...b, slug: slugifyText(b.title), publishedAt: new Date() },
      });
    }
    console.log(`[seed] inserted ${blogs.length} blogs`);
  }
}
